[package]
name = "candelatte"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.30"
gpx = "0.10"
geo-types = "0.7"
time = {version = "0.3", features = ["parsing"] }
chrono = "0.4"

[dev-dependencies]
temp-dir = "0.1"